// To add sounds to the PDA, all you need to do is add the following define ex:
// #define PDA_RINGTONE_WOOF "Woof"
// Then Add the PDA_RINGTONE_WOOF to the global list pda_ringtone_sounds, with its associative sound path
/// List of available ringtone sounds
#define PDA_RINGTONE_ALERT1 "Alert 1"
#define PDA_RINGTONE_ALERT2 "Alert 2"
#define PDA_RINGTONE_ALERT3 "Alert 3"
#define PDA_RINGTONE_ALERT4 "Alert 4"
#define PDA_RINGTONE_BELL "Bell"
#define PDA_RINGTONE_BEEP "Beep"
#define PDA_RINGTONE_BUZZ "BUZZ"
#define PDA_RINGTONE_BYONDPAGER "BYOND Pager"
#define PDA_RINGTONE_BYONDPAGERDOWN "BYOND Pager Down"
#define PDA_RINGTONE_BIKEHORN "Bikehorn"
#define PDA_RINGTONE_CHIME "Chime"
#define PDA_RINGTONE_CHORD1 "Chord 1"
#define PDA_RINGTONE_CHORD2 "Chord 2"
#define PDA_RINGTONE_CHORD3 "Chord 3"
#define PDA_RINGTONE_CODEC "Codec"
#define PDA_RINGTONE_DING "Ding"
#define PDA_RINGTONE_GRANDMA "Grandma"
#define PDA_RINGTONE_HORN "Horn"
#define PDA_RINGTONE_MAUS "Maus"
#define PDA_RINGTONE_MEOW1 "Meow 1"
#define PDA_RINGTONE_MEOW2 "Meow 2"
#define PDA_RINGTONE_MEOW3 "Meow 3"
#define PDA_RINGTONE_MEOW4 "Meow 4"
#define PDA_RINGTONE_MEOW_ELECTRIC "Meow (Electric)"
#define PDA_RINGTONE_MORSE "Morse"
#define PDA_RINGTONE_OHHIMARK "Oh Hi Mark"
#define PDA_RINGTONE_JINGLE "Mysterious Jingle"
#define PDA_RINGTONE_NORMALIZE "Normalize"
#define PDA_RINGTONE_NOT_ALPHYS "Not Alphys"
#define PDA_RINGTONE_PHONE_CHIME "Phone Chime"
#define PDA_RINGTONE_PIANO "Piano"
#define PDA_RINGTONE_PING "Ping"
#define PDA_RINGTONE_SPEAKING "Speaking"
#define PDA_RINGTONE_SPLAT "Splat"
#define PDA_RINGTONE_TARGET "Target"
#define PDA_RINGTONE_TERMINAL_NOTIF1 "Terminal Notif 1"
#define PDA_RINGTONE_WEH "Weh"

/// Default ringtone sound
#define PDA_RINGTONE_SOUND_DEFAULT PDA_RINGTONE_BEEP
